// AUTO-GENERATED. DO NOT EDIT.
// Generated by tools/generate_language_enum.py

package dev.hansholz.advancedmenubar

enum class MenuBarLanguage(val tag: String) {
    AR("ar"),
    CA("ca"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HI("hi"),
    HR("hr"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    MS("ms"),
    NL("nl"),
    NO("no"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh")
}