#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

LANG_RE = re.compile(r"^values-([a-z]{2,3})$")

TEMPLATE_HEADER = """// AUTO-GENERATED. DO NOT EDIT.
// Generated by tools/generate_language_enum.py

package dev.hansholz.advancedmenubar

enum class MenubarLanguage(val tag: String) {"""
TEMPLATE_FOOTER = """}"""

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--res-root", type=Path, default=Path("advanced-menubar/src/commonMain/composeResources"))
    ap.add_argument("--out", type=Path, required=True, help="Path to MenubarLanguage.kt")
    args = ap.parse_args()

    res_root = args.res_root.resolve()
    langs = ["en"]  # baseline always available

    if res_root.exists():
        for p in res_root.iterdir():
            if not p.is_dir():
                continue
            m = LANG_RE.fullmatch(p.name)
            if m:
                langs.append(m.group(1))

    langs = sorted(set(langs))

    def enum_name(lang: str) -> str:
        # en -> EN, de -> DE
        return lang.upper()

    lines = []
    lines.append(TEMPLATE_HEADER)

    for i, lang in enumerate(langs):
        name = enum_name(lang)
        comma = "," if i < len(langs) - 1 else ""
        lines.append(f"    {name}(\"{lang}\"){comma}")

    lines.append(TEMPLATE_FOOTER)

    out = args.out.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} with {len(langs)} languages")

if __name__ == "__main__":
    main()